# Generated by Django 4.2.27 on 2026-01-17 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('marital_status', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('languages', models.CharField(blank=True, max_length=255)),
                ('applied_for', models.CharField(max_length=150)),
                ('expected_workplace', models.CharField(blank=True, max_length=150)),
                ('expected_salary', models.IntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=150)),
                ('google_map', models.BooleanField(default=False)),
                ('vehicle_known', models.CharField(blank=True, max_length=255)),
                ('vehicle_transmission', models.CharField(blank=True, max_length=50)),
                ('departure_from_india_days', models.PositiveIntegerField(blank=True, null=True)),
                ('price_sar', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('deployed', 'Deployed')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='candidates/photos/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatePassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_type', models.CharField(choices=[('ECNR', 'ECNR'), ('ECR', 'ECR')], max_length=10)),
                ('date_of_issue', models.DateField()),
                ('date_of_expiry', models.DateField()),
                ('place_of_issue', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('passport_in_office', models.BooleanField(default=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_medically_fit', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('period_years', models.PositiveIntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.candidate')),
            ],
        ),
    ]
